version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_micros_2
    environment:
      POSTGRES_DB: users_micros_2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
